package util

const (
	DOT               = "."
	COMMA             = ","
	SEMICOLON         = ""
	COLON             = ":"
	AET               = "@"
	HLINE             = "-"
	UNDERLINE         = "_"
	EMPTY             = ""
	BRACKET_LEFT      = "["
	BRACKET_RIGHT     = "]"
	BRACE_LEFT        = "{"
	BRACE_RIGHT       = "}"
	PARENTHESIS_LEFT  = "("
	PARENTHESIS_RIGHT = ")"
	SPRIT             = "/"
	AND               = "&"
	QUESTION          = "?"
	EQUAL             = "="
	PROTOCOL          = "://"
	HTTP              = "http://"
	HTTPS             = "https://"
	LF                = "\n"
	CR                = "\r"
	SPACE             = " "
)
